#!/bin/bash

DEFAULT_VCPKG_CMAKE_PATH="/home/$USER/Applications/Tools/vcpkg"
VCPKG_ROOT="${1:-$DEFAULT_VCPKG_CMAKE_PATH}"

bash test.proto_gen.sh ${VCPKG_ROOT}
bash test.flatbuffer_gen.sh ${VCPKG_ROOT}

# Make sure you go to /Projvects/ThirdParty/libbacktrace and build and install libbacktrace.

set -e

export CORELIB_ROOT=/home/$USER/Projects/cpp/CoreLibrary
export CORELIB_BOOST_ROOT=${CORELIB_ROOT}/../ThirdParty/Boost
export CORELIB_BOOST_LIB=${CORELIB_ROOT}/../ThirdParty/Boost/lib
# Not nmeeded fo Linux build
export CORELIB_BOOST_LIB_NAME_STUB=
export CORELIB_BOOST_LIB_NAME_STUB_D=
export CORELIB_VCPKG_CMAKE_PATH="${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"

# Tidy previous installation/build folders.
rm -rf build

# E.g. CORELIB_DISABLE_ASIO_TESTS=ON, disables ASIO tests, CORELIB_DISABLE_ASIO_TESTS=OFF enables ASIO tests
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="${CORELIB_VCPKG_CMAKE_PATH}" -DCORELIB_USE_STD_FILESYSTEM=ON -DCORELIB_DISABLE_ASIO_TESTS=OFF -DCORELIB_DISABLE_CSVGRID_TESTS=OFF -DCORELIB_DISABLE_DEBUGLOG_TESTS=OFF -DCORELIB_DISABLE_FILEUTILS_TESTS=OFF -DCORELIB_DISABLE_FLOAT_COMPARE_TESTS=OFF -DCORELIB_DISABLE_SORTING_TESTS=OFF -DCORELIB_DISABLE_GPROTOBUF_TESTS=OFF -DCORELIB_DISABLE_INIFILE_TESTS=OFF -DCORELIB_DISABLE_SERIALIZATIOFF_TESTS=OFF -DCORELIB_DISABLE_STRINGUTILS_TESTS=OFF -DCORELIB_DISABLE_THREADS_TESTS=OFF -DCORELIB_DISABLE_FLATBUFFER_TESTS=OFF -DCORELIB_DISABLE_MANAGED_SINGLETON_TESTS=OFF

# Perform build
cmake --build build --config Release

cd build

ctest -C Release
