// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TEST_CORE_LIB_TEST_FB_H_
#define FLATBUFFERS_GENERATED_TEST_CORE_LIB_TEST_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace core_lib_test_fb {

struct TestMessage;
struct TestMessageBuilder;
struct TestMessageT;

struct TestMessageT : public ::flatbuffers::NativeTable {
  typedef TestMessage TableType;
  std::string name{};
  uint64_t counter = 0;
  std::vector<double> values{};
};

struct TestMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TestMessageT NativeTableType;
  typedef TestMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_COUNTER = 6,
    VT_VALUES = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint64_t counter() const {
    return GetField<uint64_t>(VT_COUNTER, 0);
  }
  const ::flatbuffers::Vector<double> *values() const {
    return GetPointer<const ::flatbuffers::Vector<double> *>(VT_VALUES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint64_t>(verifier, VT_COUNTER, 8) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
  TestMessageT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TestMessageT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<TestMessage> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TestMessageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TestMessageBuilder {
  typedef TestMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(TestMessage::VT_NAME, name);
  }
  void add_counter(uint64_t counter) {
    fbb_.AddElement<uint64_t>(TestMessage::VT_COUNTER, counter, 0);
  }
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<double>> values) {
    fbb_.AddOffset(TestMessage::VT_VALUES, values);
  }
  explicit TestMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TestMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TestMessage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TestMessage> CreateTestMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    uint64_t counter = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<double>> values = 0) {
  TestMessageBuilder builder_(_fbb);
  builder_.add_counter(counter);
  builder_.add_values(values);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TestMessage> CreateTestMessageDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    uint64_t counter = 0,
    const std::vector<double> *values = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto values__ = values ? _fbb.CreateVector<double>(*values) : 0;
  return core_lib_test_fb::CreateTestMessage(
      _fbb,
      name__,
      counter,
      values__);
}

::flatbuffers::Offset<TestMessage> CreateTestMessage(::flatbuffers::FlatBufferBuilder &_fbb, const TestMessageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline TestMessageT *TestMessage::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<TestMessageT>(new TestMessageT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void TestMessage::UnPackTo(TestMessageT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = counter(); _o->counter = _e; }
  { auto _e = values(); if (_e) { _o->values.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->values[_i] = _e->Get(_i); } } else { _o->values.resize(0); } }
}

inline ::flatbuffers::Offset<TestMessage> CreateTestMessage(::flatbuffers::FlatBufferBuilder &_fbb, const TestMessageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return TestMessage::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<TestMessage> TestMessage::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TestMessageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const TestMessageT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _counter = _o->counter;
  auto _values = _o->values.size() ? _fbb.CreateVector(_o->values) : 0;
  return core_lib_test_fb::CreateTestMessage(
      _fbb,
      _name,
      _counter,
      _values);
}

inline const core_lib_test_fb::TestMessage *GetTestMessage(const void *buf) {
  return ::flatbuffers::GetRoot<core_lib_test_fb::TestMessage>(buf);
}

inline const core_lib_test_fb::TestMessage *GetSizePrefixedTestMessage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<core_lib_test_fb::TestMessage>(buf);
}

template <bool B = false>
inline bool VerifyTestMessageBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<core_lib_test_fb::TestMessage>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedTestMessageBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<core_lib_test_fb::TestMessage>(nullptr);
}

inline void FinishTestMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<core_lib_test_fb::TestMessage> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTestMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<core_lib_test_fb::TestMessage> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<core_lib_test_fb::TestMessageT> UnPackTestMessage(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<core_lib_test_fb::TestMessageT>(GetTestMessage(buf)->UnPack(res));
}

inline std::unique_ptr<core_lib_test_fb::TestMessageT> UnPackSizePrefixedTestMessage(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<core_lib_test_fb::TestMessageT>(GetSizePrefixedTestMessage(buf)->UnPack(res));
}

}  // namespace core_lib_test_fb

#endif  // FLATBUFFERS_GENERATED_TEST_CORE_LIB_TEST_FB_H_
